# Generated by Django 2.2.4 on 2019-09-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('student_class', models.CharField(max_length=30)),
                ('roll_no', models.CharField(max_length=30)),
                ('department_name', models.CharField(max_length=30)),
                ('event_name', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=30)),
                ('email_id', models.CharField(max_length=30)),
                ('date', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'database',
            },
        ),
    ]
