# Generated by Django 2.2.5 on 2019-10-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
