# Generated by Django 2.2.5 on 2020-02-07 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191003_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=20)),
                ('v_email', models.CharField(max_length=20, validators=[django.core.validators.EmailValidator()])),
                ('phone_no', models.CharField(max_length=20)),
                ('Comment', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'visitor',
            },
        ),
    ]
