# Generated by Django 2.2.5 on 2020-02-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='Comment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='v_email',
            field=models.CharField(max_length=20),
        ),
    ]
