# Generated by Django 2.2.5 on 2020-02-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200207_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='Comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='v_email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='v_name',
            field=models.CharField(max_length=200),
        ),
    ]
