# Generated by Django 2.2.5 on 2020-02-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200220_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
