# Generated by Django 2.2.5 on 2020-02-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200224_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
